# Pavia

In [1]:
from Source_Model_Utils import *
import scipy.io as sio

In [2]:
uPavia = sio.loadmat('C:\\Users\\de991521\\Desktop\\EE_297_PROJECT\\pavia\\PaviaU.mat')
gt_uPavia = sio.loadmat('C:\\Users\\de991521\\Desktop\\EE_297_PROJECT\\pavia\\PaviaU_gt.mat')
data_PV = uPavia['paviaU']
gt_PV = gt_uPavia['paviaU_gt']
print(data_PV.shape, gt_PV.shape)
data_PV = np.moveaxis(data_PV, 2, 0)
print(data_PV.shape, gt_PV.shape)

(610, 340, 103) (610, 340)
(103, 610, 340) (610, 340)


In [3]:
values,counts = np.unique(gt_PV, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[0 1 2 3 4 5 6 7 8 9] [164624   6631  18649   2099   3064   1345   5029   1330   3682    947]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
Acc_Table = Train(overlap_ratio_List = [25,50,75,95],
                  range_of_class = range_of_class,
                  Cube_size= 25,
                  Data = data_PV,
                  Gt = gt_PV,
                  Train_Test_split = 80,
                  channel = 103,
                  epochs_list = [1, 1, 1, 1],
                  batch_size_list = [16, 32, 64, 128],
                  data_name = 'Pavia',
                  Verbosity  = 1)

                     0      1
0  Test Accuracy Table  Pavia
1      Data_Overlap_25   None
2      Data_Overlap_50   None
3      Data_Overlap_75   None
4      Data_Overlap_95   None


======================================== Data with overlap ratio of 25 will be trained ========================================


Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain => (309, 103, 24, 24, 1)
Xtest  => (82, 103, 24, 24, 1)
Ytrain => (309, 9)
Ytest  => (82, 9)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 103, 24, 24,  0                                            
________________________________________

Train on 309 samples, validate on 82 samples
304/309 [============================>.] - ETA: 0s - loss: 5.9696 - categorical_accuracy: 0.1743
Epoch 00001: val_categorical_accuracy improved from -inf to 0.12195, saving model to ..\..\Trained Models\Full_Model\Pavia\Full_Model_best_Pavia_overlap_ratio_25_percent.h5
82/82 [==============================] - 1s 17ms/sample - loss: 5.3813 - categorical_accuracy: 0.1220
Test Accuracy = 0.12195122
82/82 [==============================] - 2s 21ms/sample

=============================== Confusion_matrix for data with overlap ratio of  25 is as below ===============================

[[ 9  2  0  3  0  0  0  1  0]
 [14  0  0  0  0  0  0  0  1]
 [ 3  0  0  0  0  0  0  1  0]
 [17  0  0  0  0  0  0  3  0]
 [ 3  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0]
 [ 3  0  0  1  0  0  0  2  1]]
[15 15  4 20  3  4  2 12  7]

=============================== Sub Model below will be saved to be u



======================================== Data with overlap ratio of 50 will be trained ========================================


Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain => (505, 103, 24, 24, 1)
Xtest  => (130, 103, 24, 24, 1)
Ytrain => (505, 9)
Ytest  => (130, 9)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 103, 24, 24,  0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_2[0][0]                    
________________

Train on 505 samples, validate on 130 samples
480/505 [===========================>..] - ETA: 1s - loss: 6.1232 - categorical_accuracy: 0.1896
Epoch 00001: val_categorical_accuracy improved from -inf to 0.31538, saving model to ..\..\Trained Models\Full_Model\Pavia\Full_Model_best_Pavia_overlap_ratio_50_percent.h5
130/130 [==============================] - 2s 18ms/sample - loss: 5.3425 - categorical_accuracy: 0.3154
Test Accuracy = 0.31538463
130/130 [==============================] - 3s 20ms/sample

=============================== Confusion_matrix for data with overlap ratio of  50 is as below ===============================

[[ 0  2  0  4  0  0  0 17  0]
 [ 0 17  0  2  0  0  0  9  0]
 [ 1  0  0  1  0  0  0  4  0]
 [ 0  0  0 12  0  0  0 15  0]
 [ 0  0  0  2  0  0  0  3  0]
 [ 0  6  0  0  0  0  0  3  0]
 [ 0  0  0  1  0  0  0  3  0]
 [ 0  3  0  5  0  0  0 12  0]
 [ 0  0  0  6  0  0  0  2  0]]
[23 28  6 27  5  9  4 20  8]

=============================== Sub Model below will be saved to



======================================== Data with overlap ratio of 75 will be trained ========================================


Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain => (1206, 103, 24, 24, 1)
Xtest  => (304, 103, 24, 24, 1)
Ytrain => (1206, 9)
Ytest  => (304, 9)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            (None, 103, 24, 24,  0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
___________

Train on 1206 samples, validate on 304 samples
1152/1206 [===========================>..] - ETA: 3s - loss: 5.9896 - categorical_accuracy: 0.1962
Epoch 00001: val_categorical_accuracy improved from -inf to 0.28947, saving model to ..\..\Trained Models\Full_Model\Pavia\Full_Model_best_Pavia_overlap_ratio_75_percent.h5
304/304 [==============================] - 5s 17ms/sample - loss: 5.8679 - categorical_accuracy: 0.2895
Test Accuracy = 0.28947368
304/304 [==============================] - 6s 20ms/sample

=============================== Confusion_matrix for data with overlap ratio of  75 is as below ===============================

[[ 0 34  0 19  0  0  0  0  0]
 [ 0 85  0  0  0  0  0  0  0]
 [ 0 10  0  5  0  0  0  0  0]
 [ 0 46  0  3  0  0  0  0  0]
 [ 0  9  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0]
 [ 0  7  0  2  0  0  0  0  0]
 [ 0 38  0  3  0  0  0  0  0]
 [ 0  9  0  5  0  0  0  0  0]]
[53 85 15 49 10 28  9 41 14]

=============================== Sub Model below will be saved



======================================== Data with overlap ratio of 95 will be trained ========================================


Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain => (13491, 103, 24, 24, 1)
Xtest  => (3377, 103, 24, 24, 1)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            (None, 103, 24, 24,  0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_4[0][0

Train on 13491 samples, validate on 3377 samples
13440/13491 [============================>.] - ETA: 2s - loss: 4.6128 - categorical_accuracy: 0.5000
Epoch 00001: val_categorical_accuracy improved from -inf to 0.36068, saving model to ..\..\Trained Models\Full_Model\Pavia\Full_Model_best_Pavia_overlap_ratio_95_percent.h5
3377/3377 [==============================] - 64s 19ms/sample - loss: 4.6726 - categorical_accuracy: 0.3607
Test Accuracy = 0.36067516
3377/3377 [==============================] - 65s 19ms/sample

=============================== Confusion_matrix for data with overlap ratio of  95 is as below ===============================

[[   1   18    1  463   75    9    0    0    1]
 [   0 1009    0  145   95    0    0    0    0]
 [   0    1    0   83   70    0    0    1    0]
 [   0    4    0   88  190    0    0    0    0]
 [   0    0    0   10  118    0    0    0    0]
 [   0  419    0    8    8    0    0    0    0]
 [   4   18    0   34   28   20    0    0   17]
 [   0   66    0

In [5]:
Acc_Table

0         1
0  Test Accuracy Table  0.121951
1      Data_Overlap_25  0.315385
2      Data_Overlap_50  0.289474
3      Data_Overlap_75  0.360675
4      Data_Overlap_95       NaN